version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: smartwaste-mongodb
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: smart_waste_db
    volumes:
      - mongo_data:/data/db

  ai-service:
    build:
      context: ./ai-service
      dockerfile: Dockerfile
    container_name: smartwaste-ai-service
    restart: always
    ports:
      - '8000:8000'
    environment:
      - PORT=8000
    depends_on:
      - mongodb

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: smartwaste-backend
    restart: always
    ports:
      - '5000:5000'
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongodb:27017/smart_waste_db
      - JWT_SECRET=super_secret_jwt_key_srinagar_smart_waste_2026_msc_ai
      - AI_SERVICE_URL=http://ai-service:8000
    depends_on:
      - mongodb
      - ai-service

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: smartwaste-frontend
    restart: always
    ports:
      - '5173:80'
    depends_on:
      - backend

volumes:
  mongo_data:
